version: "3.9"

services:
    web:
      restart: always
      build:
        context: ./
        dockerfile: Dockerfile.prod
      command: daphne -b 0.0.0.0 -p 8000 auctsite.asgi:application
      volumes:
        - static_volume:/home/app/web/static
        - media_volume:/home/app/web/media
      expose:
        - 8000
      env_file:
        - ./.env.prod
      depends_on:
        - db_psql
        - db_redis

    celery:
      restart: always
      build:
        context: ./
        dockerfile: Dockerfile.prod
      command: python3 start_prod_server.py
      env_file:
        - ./.env.prod
      depends_on:
        - db_redis
        - db_psql
        - nginx
        - web

    dashboard:
      restart: always
      build:
        context: ./
        dockerfile: Dockerfile.prod
      command: celery flower -A auctsite --port=5555 --broker=redis://redis:6379/0
      ports:
        - 5555:5555
      env_file:
        - ./.env.prod
      depends_on:
        - web
        - nginx
        - db_redis
        - celery
        - db_psql


    db_psql:
      restart: always
      image: postgres:14.1-alpine
      volumes:
        - postgres_data:/postgresql/data
      env_file:
        - ./.env.db.prod
    
    db_redis:
      restart: always
      image: redis:6.2.6
      volumes:
        - redis_data:/redis/data

    nginx:
      restart: always
      build: ./nginx
      volumes:
        - static_volume:/home/app/web/static
        - media_volume:/home/app/web/media
      ports:
        - 1337:80
      depends_on:
        - web

volumes:
  redis_data:
  postgres_data:
  static_volume:
  media_volume:
