# Generated by Django 3.2.9 on 2021-11-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
